import { Geist, Geist_Mono } from "next/font/google";
import { GoogleOAuthProvider } from "@react-oauth/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { CartProvider } from "@/context/CartContext";
import localFont from "next/font/local";

const nexa = localFont({
  src: [
    {
      path: "../fonts/Nexa-ExtraLight.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../fonts/Nexa-Heavy.ttf",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-nexa",
});

const seasons = localFont({
  src: [
    {
      path: "../fonts/The Seasons Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../fonts/The Seasons Light Italic.ttf",
      weight: "300",
      style: "italic",
    },
    {
      path: "../fonts/The Seasons Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/The Seasons Italic.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../fonts/The Seasons Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/The Seasons Bold Italic.ttf",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-seasons",
});

export const metadata = {
  title: "KeptAlive",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script
          src="https://accounts.google.com/gsi/client"
          async
          defer
        ></script>
      </head>
      <body
        className={`${nexa.variable}
  ${seasons.variable} antialiased`}
      >
        <Toaster position="top-right" />
        <CartProvider>
          <GoogleOAuthProvider
            clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID}
          >
            {children}
          </GoogleOAuthProvider>
        </CartProvider>
      </body>
    </html>
  );
}
